/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
import { AttributesType, EventType, SlotType } from "./utils/utils";
import { Element } from "@stencil/core";
export { AttributesType, EventType, SlotType } from "./utils/utils";
export { Element } from "@stencil/core";
export namespace Components {
    interface AccessibilityTab {
        "landmarkDisplay"?: boolean;
        /**
         * @deprecated use camelCase instead. Support for dash-casing will be removed in Stencil v5.
         */
        "landmark-display"?: boolean;
    }
    interface AttributeTab {
        "attributeObject": Array<AttributesType>;
        "displayElement": Element;
    }
    interface CodeFrame {
        "accessibility"?: boolean;
        "framework"?: 'html' | 'react' | 'vue' | 'angular';
        "gcdsPath"?: string;
        /**
         * @deprecated use camelCase instead. Support for dash-casing will be removed in Stencil v5.
         */
        "gcds-path"?: string;
        "landmarkDisplay"?: boolean;
        /**
         * @deprecated use camelCase instead. Support for dash-casing will be removed in Stencil v5.
         */
        "landmark-display"?: boolean;
        "source": string;
    }
    interface EventsTab {
        "eventObject": Array<EventType> | undefined;
    }
    interface GcdsExtCodeDisplay {
        "accessibility"?: boolean;
        "attrs"?: string | Array<AttributesType>;
        "events"?: string | Array<EventType>;
        "framework"?: 'html' | 'react' | 'vue' | 'angular';
        "gcdsPath"?: string;
        /**
         * @deprecated use camelCase instead. Support for dash-casing will be removed in Stencil v5.
         */
        "gcds-path"?: string;
        "landmarkDisplay"?: boolean;
        /**
         * @deprecated use camelCase instead. Support for dash-casing will be removed in Stencil v5.
         */
        "landmark-display"?: boolean;
        "slots"?: string | Array<SlotType>;
    }
    interface SlotsTab {
        "displayElement": Element;
        "slotHistory": Object | undefined;
        "slotObject": Array<SlotType> | undefined;
    }
}
export interface AttributeTabCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLAttributeTabElement;
}
export interface CodeFrameCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLCodeFrameElement;
}
export interface SlotsTabCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLSlotsTabElement;
}
declare global {
    interface HTMLAccessibilityTabElement extends Components.AccessibilityTab, HTMLStencilElement {
    }
    var HTMLAccessibilityTabElement: {
        prototype: HTMLAccessibilityTabElement;
        new (): HTMLAccessibilityTabElement;
    };
    interface HTMLAttributeTabElementEventMap {
        "attributeChange": Object;
        "statusUpdate": Object;
    }
    interface HTMLAttributeTabElement extends Components.AttributeTab, HTMLStencilElement {
        addEventListener<K extends keyof HTMLAttributeTabElementEventMap>(type: K, listener: (this: HTMLAttributeTabElement, ev: AttributeTabCustomEvent<HTMLAttributeTabElementEventMap[K]>) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | AddEventListenerOptions): void;
        removeEventListener<K extends keyof HTMLAttributeTabElementEventMap>(type: K, listener: (this: HTMLAttributeTabElement, ev: AttributeTabCustomEvent<HTMLAttributeTabElementEventMap[K]>) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | EventListenerOptions): void;
    }
    var HTMLAttributeTabElement: {
        prototype: HTMLAttributeTabElement;
        new (): HTMLAttributeTabElement;
    };
    interface HTMLCodeFrameElementEventMap {
        "statusUpdate": Object;
    }
    interface HTMLCodeFrameElement extends Components.CodeFrame, HTMLStencilElement {
        addEventListener<K extends keyof HTMLCodeFrameElementEventMap>(type: K, listener: (this: HTMLCodeFrameElement, ev: CodeFrameCustomEvent<HTMLCodeFrameElementEventMap[K]>) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | AddEventListenerOptions): void;
        removeEventListener<K extends keyof HTMLCodeFrameElementEventMap>(type: K, listener: (this: HTMLCodeFrameElement, ev: CodeFrameCustomEvent<HTMLCodeFrameElementEventMap[K]>) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | EventListenerOptions): void;
    }
    var HTMLCodeFrameElement: {
        prototype: HTMLCodeFrameElement;
        new (): HTMLCodeFrameElement;
    };
    interface HTMLEventsTabElement extends Components.EventsTab, HTMLStencilElement {
    }
    var HTMLEventsTabElement: {
        prototype: HTMLEventsTabElement;
        new (): HTMLEventsTabElement;
    };
    interface HTMLGcdsExtCodeDisplayElement extends Components.GcdsExtCodeDisplay, HTMLStencilElement {
    }
    var HTMLGcdsExtCodeDisplayElement: {
        prototype: HTMLGcdsExtCodeDisplayElement;
        new (): HTMLGcdsExtCodeDisplayElement;
    };
    interface HTMLSlotsTabElementEventMap {
        "slotValueChange": Object;
        "statusUpdate": Object;
    }
    interface HTMLSlotsTabElement extends Components.SlotsTab, HTMLStencilElement {
        addEventListener<K extends keyof HTMLSlotsTabElementEventMap>(type: K, listener: (this: HTMLSlotsTabElement, ev: SlotsTabCustomEvent<HTMLSlotsTabElementEventMap[K]>) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | AddEventListenerOptions): void;
        removeEventListener<K extends keyof HTMLSlotsTabElementEventMap>(type: K, listener: (this: HTMLSlotsTabElement, ev: SlotsTabCustomEvent<HTMLSlotsTabElementEventMap[K]>) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | EventListenerOptions): void;
    }
    var HTMLSlotsTabElement: {
        prototype: HTMLSlotsTabElement;
        new (): HTMLSlotsTabElement;
    };
    interface HTMLElementTagNameMap {
        "accessibility-tab": HTMLAccessibilityTabElement;
        "attribute-tab": HTMLAttributeTabElement;
        "code-frame": HTMLCodeFrameElement;
        "events-tab": HTMLEventsTabElement;
        "gcds-ext-code-display": HTMLGcdsExtCodeDisplayElement;
        "slots-tab": HTMLSlotsTabElement;
    }
}
declare namespace LocalJSX {
    interface AccessibilityTab {
        "landmarkDisplay"?: boolean;
        /**
         * @deprecated use camelCase instead. Support for dash-casing will be removed in Stencil v5.
         */
        "landmark-display"?: boolean;
    }
    interface AttributeTab {
        "attributeObject"?: Array<AttributesType>;
        "displayElement": Element;
        "onAttributeChange"?: (event: AttributeTabCustomEvent<Object>) => void;
        "onStatusUpdate"?: (event: AttributeTabCustomEvent<Object>) => void;
    }
    interface CodeFrame {
        "accessibility"?: boolean;
        "framework"?: 'html' | 'react' | 'vue' | 'angular';
        "gcdsPath"?: string;
        /**
         * @deprecated use camelCase instead. Support for dash-casing will be removed in Stencil v5.
         */
        "gcds-path"?: string;
        "landmarkDisplay"?: boolean;
        /**
         * @deprecated use camelCase instead. Support for dash-casing will be removed in Stencil v5.
         */
        "landmark-display"?: boolean;
        "onStatusUpdate"?: (event: CodeFrameCustomEvent<Object>) => void;
        "source"?: string;
    }
    interface EventsTab {
        "eventObject"?: Array<EventType> | undefined;
    }
    interface GcdsExtCodeDisplay {
        "accessibility"?: boolean;
        "attrs"?: string | Array<AttributesType>;
        "events"?: string | Array<EventType>;
        "framework"?: 'html' | 'react' | 'vue' | 'angular';
        "gcdsPath"?: string;
        /**
         * @deprecated use camelCase instead. Support for dash-casing will be removed in Stencil v5.
         */
        "gcds-path"?: string;
        "landmarkDisplay"?: boolean;
        /**
         * @deprecated use camelCase instead. Support for dash-casing will be removed in Stencil v5.
         */
        "landmark-display"?: boolean;
        "slots"?: string | Array<SlotType>;
    }
    interface SlotsTab {
        "displayElement": Element;
        "onSlotValueChange"?: (event: SlotsTabCustomEvent<Object>) => void;
        "onStatusUpdate"?: (event: SlotsTabCustomEvent<Object>) => void;
        "slotHistory"?: Object | undefined;
        "slotObject"?: Array<SlotType> | undefined;
    }
    interface IntrinsicElements {
        "accessibility-tab": AccessibilityTab;
        "attribute-tab": AttributeTab;
        "code-frame": CodeFrame;
        "events-tab": EventsTab;
        "gcds-ext-code-display": GcdsExtCodeDisplay;
        "slots-tab": SlotsTab;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "accessibility-tab": LocalJSX.AccessibilityTab & JSXBase.HTMLAttributes<HTMLAccessibilityTabElement>;
            "attribute-tab": LocalJSX.AttributeTab & JSXBase.HTMLAttributes<HTMLAttributeTabElement>;
            "code-frame": LocalJSX.CodeFrame & JSXBase.HTMLAttributes<HTMLCodeFrameElement>;
            "events-tab": LocalJSX.EventsTab & JSXBase.HTMLAttributes<HTMLEventsTabElement>;
            "gcds-ext-code-display": LocalJSX.GcdsExtCodeDisplay & JSXBase.HTMLAttributes<HTMLGcdsExtCodeDisplayElement>;
            "slots-tab": LocalJSX.SlotsTab & JSXBase.HTMLAttributes<HTMLSlotsTabElement>;
        }
    }
}
